/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPopupsRouteImport } from './routes/admin.popups'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTrustRouteImport } from './routes/admin.trust'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as DealsSlugRouteImport } from './routes/deals.$slug'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as ApiPublicV1CategoriesRouteImport } from './routes/api/public/v1/categories'
import { Route as ApiPublicV1CollectionsRouteImport } from './routes/api/public/v1/collections'
import { Route as ApiPublicV1DealsRouteImport } from './routes/api/public/v1/deals'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1HeroSlidesRouteImport } from './routes/api/public/v1/hero-slides'
import { Route as ApiPublicV1ProfileRouteImport } from './routes/api/public/v1/profile'
import { Route as ApiPublicV1ReviewsRouteImport } from './routes/api/public/v1/reviews'
import { Route as ApiPublicV1SettingsRouteImport } from './routes/api/public/v1/settings'
import { Route as ApiPublicV1AdminCustomersRouteImport } from './routes/api/public/v1/admin.customers'
import { Route as ApiPublicV1AdminOrdersRouteImport } from './routes/api/public/v1/admin.orders'
import { Route as ApiPublicV1AdminProductsRouteImport } from './routes/api/public/v1/admin.products'
import { Route as ApiPublicV1AdminStatsRouteImport } from './routes/api/public/v1/admin.stats'
import { Route as ApiPublicV1AuthLoginRouteImport } from './routes/api/public/v1/auth.login'
import { Route as ApiPublicV1AuthLogoutRouteImport } from './routes/api/public/v1/auth.logout'
import { Route as ApiPublicV1AuthRefreshRouteImport } from './routes/api/public/v1/auth.refresh'
import { Route as ApiPublicV1AuthSessionRouteImport } from './routes/api/public/v1/auth.session'
import { Route as ApiPublicV1AuthSignupRouteImport } from './routes/api/public/v1/auth.signup'
import { Route as ApiPublicV1BlogIndexRouteImport } from './routes/api/public/v1/blog.index'
import { Route as ApiPublicV1BlogSlugRouteImport } from './routes/api/public/v1/blog.$slug'
import { Route as ApiPublicV1CouponsValidateRouteImport } from './routes/api/public/v1/coupons.validate'
import { Route as ApiPublicV1OrdersIndexRouteImport } from './routes/api/public/v1/orders.index'
import { Route as ApiPublicV1OrdersOrderNumberRouteImport } from './routes/api/public/v1/orders.$orderNumber'
import { Route as ApiPublicV1ProductsIndexRouteImport } from './routes/api/public/v1/products.index'
import { Route as ApiPublicV1ProductsSlugRouteImport } from './routes/api/public/v1/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupsRoute = AdminPopupsRouteImport.update({
  id: '/popups',
  path: '/popups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrustRoute = AdminTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsSlugRoute = DealsSlugRouteImport.update({
  id: '/deals/$slug',
  path: '/deals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CategoriesRoute = ApiPublicV1CategoriesRouteImport.update({
  id: '/api/public/v1/categories',
  path: '/api/public/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CollectionsRoute = ApiPublicV1CollectionsRouteImport.update({
  id: '/api/public/v1/collections',
  path: '/api/public/v1/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DealsRoute = ApiPublicV1DealsRouteImport.update({
  id: '/api/public/v1/deals',
  path: '/api/public/v1/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HeroSlidesRoute = ApiPublicV1HeroSlidesRouteImport.update({
  id: '/api/public/v1/hero-slides',
  path: '/api/public/v1/hero-slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProfileRoute = ApiPublicV1ProfileRouteImport.update({
  id: '/api/public/v1/profile',
  path: '/api/public/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReviewsRoute = ApiPublicV1ReviewsRouteImport.update({
  id: '/api/public/v1/reviews',
  path: '/api/public/v1/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SettingsRoute = ApiPublicV1SettingsRouteImport.update({
  id: '/api/public/v1/settings',
  path: '/api/public/v1/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AdminCustomersRoute =
  ApiPublicV1AdminCustomersRouteImport.update({
    id: '/api/public/v1/admin/customers',
    path: '/api/public/v1/admin/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AdminOrdersRoute = ApiPublicV1AdminOrdersRouteImport.update({
  id: '/api/public/v1/admin/orders',
  path: '/api/public/v1/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AdminProductsRoute =
  ApiPublicV1AdminProductsRouteImport.update({
    id: '/api/public/v1/admin/products',
    path: '/api/public/v1/admin/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AdminStatsRoute = ApiPublicV1AdminStatsRouteImport.update({
  id: '/api/public/v1/admin/stats',
  path: '/api/public/v1/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthLoginRoute = ApiPublicV1AuthLoginRouteImport.update({
  id: '/api/public/v1/auth/login',
  path: '/api/public/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthLogoutRoute = ApiPublicV1AuthLogoutRouteImport.update({
  id: '/api/public/v1/auth/logout',
  path: '/api/public/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthRefreshRoute = ApiPublicV1AuthRefreshRouteImport.update({
  id: '/api/public/v1/auth/refresh',
  path: '/api/public/v1/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthSessionRoute = ApiPublicV1AuthSessionRouteImport.update({
  id: '/api/public/v1/auth/session',
  path: '/api/public/v1/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthSignupRoute = ApiPublicV1AuthSignupRouteImport.update({
  id: '/api/public/v1/auth/signup',
  path: '/api/public/v1/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BlogIndexRoute = ApiPublicV1BlogIndexRouteImport.update({
  id: '/api/public/v1/blog/',
  path: '/api/public/v1/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BlogSlugRoute = ApiPublicV1BlogSlugRouteImport.update({
  id: '/api/public/v1/blog/$slug',
  path: '/api/public/v1/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CouponsValidateRoute =
  ApiPublicV1CouponsValidateRouteImport.update({
    id: '/api/public/v1/coupons/validate',
    path: '/api/public/v1/coupons/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIndexRoute = ApiPublicV1OrdersIndexRouteImport.update({
  id: '/api/public/v1/orders/',
  path: '/api/public/v1/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrdersOrderNumberRoute =
  ApiPublicV1OrdersOrderNumberRouteImport.update({
    id: '/api/public/v1/orders/$orderNumber',
    path: '/api/public/v1/orders/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ProductsIndexRoute =
  ApiPublicV1ProductsIndexRouteImport.update({
    id: '/api/public/v1/products/',
    path: '/api/public/v1/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ProductsSlugRoute = ApiPublicV1ProductsSlugRouteImport.update({
  id: '/api/public/v1/products/$slug',
  path: '/api/public/v1/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/wishlist': typeof WishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/api/public/v1/categories': typeof ApiPublicV1CategoriesRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/deals': typeof ApiPublicV1DealsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/hero-slides': typeof ApiPublicV1HeroSlidesRoute
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/reviews': typeof ApiPublicV1ReviewsRoute
  '/api/public/v1/settings': typeof ApiPublicV1SettingsRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/customers': typeof ApiPublicV1AdminCustomersRoute
  '/api/public/v1/admin/orders': typeof ApiPublicV1AdminOrdersRoute
  '/api/public/v1/admin/products': typeof ApiPublicV1AdminProductsRoute
  '/api/public/v1/admin/stats': typeof ApiPublicV1AdminStatsRoute
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/logout': typeof ApiPublicV1AuthLogoutRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/auth/session': typeof ApiPublicV1AuthSessionRoute
  '/api/public/v1/auth/signup': typeof ApiPublicV1AuthSignupRoute
  '/api/public/v1/blog/$slug': typeof ApiPublicV1BlogSlugRoute
  '/api/public/v1/coupons/validate': typeof ApiPublicV1CouponsValidateRoute
  '/api/public/v1/orders/$orderNumber': typeof ApiPublicV1OrdersOrderNumberRoute
  '/api/public/v1/products/$slug': typeof ApiPublicV1ProductsSlugRoute
  '/api/public/v1/blog/': typeof ApiPublicV1BlogIndexRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/products/': typeof ApiPublicV1ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/wishlist': typeof WishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/deals': typeof DealsIndexRoute
  '/api/public/v1/categories': typeof ApiPublicV1CategoriesRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/deals': typeof ApiPublicV1DealsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/hero-slides': typeof ApiPublicV1HeroSlidesRoute
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/reviews': typeof ApiPublicV1ReviewsRoute
  '/api/public/v1/settings': typeof ApiPublicV1SettingsRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/customers': typeof ApiPublicV1AdminCustomersRoute
  '/api/public/v1/admin/orders': typeof ApiPublicV1AdminOrdersRoute
  '/api/public/v1/admin/products': typeof ApiPublicV1AdminProductsRoute
  '/api/public/v1/admin/stats': typeof ApiPublicV1AdminStatsRoute
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/logout': typeof ApiPublicV1AuthLogoutRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/auth/session': typeof ApiPublicV1AuthSessionRoute
  '/api/public/v1/auth/signup': typeof ApiPublicV1AuthSignupRoute
  '/api/public/v1/blog/$slug': typeof ApiPublicV1BlogSlugRoute
  '/api/public/v1/coupons/validate': typeof ApiPublicV1CouponsValidateRoute
  '/api/public/v1/orders/$orderNumber': typeof ApiPublicV1OrdersOrderNumberRoute
  '/api/public/v1/products/$slug': typeof ApiPublicV1ProductsSlugRoute
  '/api/public/v1/blog': typeof ApiPublicV1BlogIndexRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/wishlist': typeof WishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/api/public/v1/categories': typeof ApiPublicV1CategoriesRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/deals': typeof ApiPublicV1DealsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/hero-slides': typeof ApiPublicV1HeroSlidesRoute
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/reviews': typeof ApiPublicV1ReviewsRoute
  '/api/public/v1/settings': typeof ApiPublicV1SettingsRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/customers': typeof ApiPublicV1AdminCustomersRoute
  '/api/public/v1/admin/orders': typeof ApiPublicV1AdminOrdersRoute
  '/api/public/v1/admin/products': typeof ApiPublicV1AdminProductsRoute
  '/api/public/v1/admin/stats': typeof ApiPublicV1AdminStatsRoute
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/logout': typeof ApiPublicV1AuthLogoutRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/auth/session': typeof ApiPublicV1AuthSessionRoute
  '/api/public/v1/auth/signup': typeof ApiPublicV1AuthSignupRoute
  '/api/public/v1/blog/$slug': typeof ApiPublicV1BlogSlugRoute
  '/api/public/v1/coupons/validate': typeof ApiPublicV1CouponsValidateRoute
  '/api/public/v1/orders/$orderNumber': typeof ApiPublicV1OrdersOrderNumberRoute
  '/api/public/v1/products/$slug': typeof ApiPublicV1ProductsSlugRoute
  '/api/public/v1/blog/': typeof ApiPublicV1BlogIndexRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/products/': typeof ApiPublicV1ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/trust'
    | '/wishlist'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/deals'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/popups'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/trust'
    | '/api/chat'
    | '/collections/$slug'
    | '/deals/$slug'
    | '/policies/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/collections/'
    | '/deals/'
    | '/api/public/v1/categories'
    | '/api/public/v1/collections'
    | '/api/public/v1/deals'
    | '/api/public/v1/health'
    | '/api/public/v1/hero-slides'
    | '/api/public/v1/profile'
    | '/api/public/v1/reviews'
    | '/api/public/v1/settings'
    | '/api/public/v1/'
    | '/api/public/v1/admin/customers'
    | '/api/public/v1/admin/orders'
    | '/api/public/v1/admin/products'
    | '/api/public/v1/admin/stats'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/logout'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/auth/session'
    | '/api/public/v1/auth/signup'
    | '/api/public/v1/blog/$slug'
    | '/api/public/v1/coupons/validate'
    | '/api/public/v1/orders/$orderNumber'
    | '/api/public/v1/products/$slug'
    | '/api/public/v1/blog/'
    | '/api/public/v1/orders/'
    | '/api/public/v1/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/trust'
    | '/wishlist'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/deals'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/popups'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/trust'
    | '/api/chat'
    | '/collections/$slug'
    | '/deals/$slug'
    | '/policies/$slug'
    | '/product/$slug'
    | '/admin'
    | '/collections'
    | '/deals'
    | '/api/public/v1/categories'
    | '/api/public/v1/collections'
    | '/api/public/v1/deals'
    | '/api/public/v1/health'
    | '/api/public/v1/hero-slides'
    | '/api/public/v1/profile'
    | '/api/public/v1/reviews'
    | '/api/public/v1/settings'
    | '/api/public/v1'
    | '/api/public/v1/admin/customers'
    | '/api/public/v1/admin/orders'
    | '/api/public/v1/admin/products'
    | '/api/public/v1/admin/stats'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/logout'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/auth/session'
    | '/api/public/v1/auth/signup'
    | '/api/public/v1/blog/$slug'
    | '/api/public/v1/coupons/validate'
    | '/api/public/v1/orders/$orderNumber'
    | '/api/public/v1/products/$slug'
    | '/api/public/v1/blog'
    | '/api/public/v1/orders'
    | '/api/public/v1/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/trust'
    | '/wishlist'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/deals'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/popups'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/trust'
    | '/api/chat'
    | '/collections/$slug'
    | '/deals/$slug'
    | '/policies/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/collections/'
    | '/deals/'
    | '/api/public/v1/categories'
    | '/api/public/v1/collections'
    | '/api/public/v1/deals'
    | '/api/public/v1/health'
    | '/api/public/v1/hero-slides'
    | '/api/public/v1/profile'
    | '/api/public/v1/reviews'
    | '/api/public/v1/settings'
    | '/api/public/v1/'
    | '/api/public/v1/admin/customers'
    | '/api/public/v1/admin/orders'
    | '/api/public/v1/admin/products'
    | '/api/public/v1/admin/stats'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/logout'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/auth/session'
    | '/api/public/v1/auth/signup'
    | '/api/public/v1/blog/$slug'
    | '/api/public/v1/coupons/validate'
    | '/api/public/v1/orders/$orderNumber'
    | '/api/public/v1/products/$slug'
    | '/api/public/v1/blog/'
    | '/api/public/v1/orders/'
    | '/api/public/v1/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  TrustRoute: typeof TrustRoute
  WishlistRoute: typeof WishlistRoute
  ApiChatRoute: typeof ApiChatRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  DealsSlugRoute: typeof DealsSlugRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  ApiPublicV1CategoriesRoute: typeof ApiPublicV1CategoriesRoute
  ApiPublicV1CollectionsRoute: typeof ApiPublicV1CollectionsRoute
  ApiPublicV1DealsRoute: typeof ApiPublicV1DealsRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1HeroSlidesRoute: typeof ApiPublicV1HeroSlidesRoute
  ApiPublicV1ProfileRoute: typeof ApiPublicV1ProfileRoute
  ApiPublicV1ReviewsRoute: typeof ApiPublicV1ReviewsRoute
  ApiPublicV1SettingsRoute: typeof ApiPublicV1SettingsRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
  ApiPublicV1AdminCustomersRoute: typeof ApiPublicV1AdminCustomersRoute
  ApiPublicV1AdminOrdersRoute: typeof ApiPublicV1AdminOrdersRoute
  ApiPublicV1AdminProductsRoute: typeof ApiPublicV1AdminProductsRoute
  ApiPublicV1AdminStatsRoute: typeof ApiPublicV1AdminStatsRoute
  ApiPublicV1AuthLoginRoute: typeof ApiPublicV1AuthLoginRoute
  ApiPublicV1AuthLogoutRoute: typeof ApiPublicV1AuthLogoutRoute
  ApiPublicV1AuthRefreshRoute: typeof ApiPublicV1AuthRefreshRoute
  ApiPublicV1AuthSessionRoute: typeof ApiPublicV1AuthSessionRoute
  ApiPublicV1AuthSignupRoute: typeof ApiPublicV1AuthSignupRoute
  ApiPublicV1BlogSlugRoute: typeof ApiPublicV1BlogSlugRoute
  ApiPublicV1CouponsValidateRoute: typeof ApiPublicV1CouponsValidateRoute
  ApiPublicV1OrdersOrderNumberRoute: typeof ApiPublicV1OrdersOrderNumberRoute
  ApiPublicV1ProductsSlugRoute: typeof ApiPublicV1ProductsSlugRoute
  ApiPublicV1BlogIndexRoute: typeof ApiPublicV1BlogIndexRoute
  ApiPublicV1OrdersIndexRoute: typeof ApiPublicV1OrdersIndexRoute
  ApiPublicV1ProductsIndexRoute: typeof ApiPublicV1ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popups': {
      id: '/admin/popups'
      path: '/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AdminPopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trust': {
      id: '/admin/trust'
      path: '/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AdminTrustRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$slug': {
      id: '/deals/$slug'
      path: '/deals/$slug'
      fullPath: '/deals/$slug'
      preLoaderRoute: typeof DealsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/categories': {
      id: '/api/public/v1/categories'
      path: '/api/public/v1/categories'
      fullPath: '/api/public/v1/categories'
      preLoaderRoute: typeof ApiPublicV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/collections': {
      id: '/api/public/v1/collections'
      path: '/api/public/v1/collections'
      fullPath: '/api/public/v1/collections'
      preLoaderRoute: typeof ApiPublicV1CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/deals': {
      id: '/api/public/v1/deals'
      path: '/api/public/v1/deals'
      fullPath: '/api/public/v1/deals'
      preLoaderRoute: typeof ApiPublicV1DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/hero-slides': {
      id: '/api/public/v1/hero-slides'
      path: '/api/public/v1/hero-slides'
      fullPath: '/api/public/v1/hero-slides'
      preLoaderRoute: typeof ApiPublicV1HeroSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/profile': {
      id: '/api/public/v1/profile'
      path: '/api/public/v1/profile'
      fullPath: '/api/public/v1/profile'
      preLoaderRoute: typeof ApiPublicV1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/reviews': {
      id: '/api/public/v1/reviews'
      path: '/api/public/v1/reviews'
      fullPath: '/api/public/v1/reviews'
      preLoaderRoute: typeof ApiPublicV1ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/settings': {
      id: '/api/public/v1/settings'
      path: '/api/public/v1/settings'
      fullPath: '/api/public/v1/settings'
      preLoaderRoute: typeof ApiPublicV1SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/admin/customers': {
      id: '/api/public/v1/admin/customers'
      path: '/api/public/v1/admin/customers'
      fullPath: '/api/public/v1/admin/customers'
      preLoaderRoute: typeof ApiPublicV1AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/admin/orders': {
      id: '/api/public/v1/admin/orders'
      path: '/api/public/v1/admin/orders'
      fullPath: '/api/public/v1/admin/orders'
      preLoaderRoute: typeof ApiPublicV1AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/admin/products': {
      id: '/api/public/v1/admin/products'
      path: '/api/public/v1/admin/products'
      fullPath: '/api/public/v1/admin/products'
      preLoaderRoute: typeof ApiPublicV1AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/admin/stats': {
      id: '/api/public/v1/admin/stats'
      path: '/api/public/v1/admin/stats'
      fullPath: '/api/public/v1/admin/stats'
      preLoaderRoute: typeof ApiPublicV1AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/login': {
      id: '/api/public/v1/auth/login'
      path: '/api/public/v1/auth/login'
      fullPath: '/api/public/v1/auth/login'
      preLoaderRoute: typeof ApiPublicV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/logout': {
      id: '/api/public/v1/auth/logout'
      path: '/api/public/v1/auth/logout'
      fullPath: '/api/public/v1/auth/logout'
      preLoaderRoute: typeof ApiPublicV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/refresh': {
      id: '/api/public/v1/auth/refresh'
      path: '/api/public/v1/auth/refresh'
      fullPath: '/api/public/v1/auth/refresh'
      preLoaderRoute: typeof ApiPublicV1AuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/session': {
      id: '/api/public/v1/auth/session'
      path: '/api/public/v1/auth/session'
      fullPath: '/api/public/v1/auth/session'
      preLoaderRoute: typeof ApiPublicV1AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/signup': {
      id: '/api/public/v1/auth/signup'
      path: '/api/public/v1/auth/signup'
      fullPath: '/api/public/v1/auth/signup'
      preLoaderRoute: typeof ApiPublicV1AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/blog/': {
      id: '/api/public/v1/blog/'
      path: '/api/public/v1/blog'
      fullPath: '/api/public/v1/blog/'
      preLoaderRoute: typeof ApiPublicV1BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/blog/$slug': {
      id: '/api/public/v1/blog/$slug'
      path: '/api/public/v1/blog/$slug'
      fullPath: '/api/public/v1/blog/$slug'
      preLoaderRoute: typeof ApiPublicV1BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/coupons/validate': {
      id: '/api/public/v1/coupons/validate'
      path: '/api/public/v1/coupons/validate'
      fullPath: '/api/public/v1/coupons/validate'
      preLoaderRoute: typeof ApiPublicV1CouponsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/': {
      id: '/api/public/v1/orders/'
      path: '/api/public/v1/orders'
      fullPath: '/api/public/v1/orders/'
      preLoaderRoute: typeof ApiPublicV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$orderNumber': {
      id: '/api/public/v1/orders/$orderNumber'
      path: '/api/public/v1/orders/$orderNumber'
      fullPath: '/api/public/v1/orders/$orderNumber'
      preLoaderRoute: typeof ApiPublicV1OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/': {
      id: '/api/public/v1/products/'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products/'
      preLoaderRoute: typeof ApiPublicV1ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$slug': {
      id: '/api/public/v1/products/$slug'
      path: '/api/public/v1/products/$slug'
      fullPath: '/api/public/v1/products/$slug'
      preLoaderRoute: typeof ApiPublicV1ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPopupsRoute: typeof AdminPopupsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrustRoute: typeof AdminTrustRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPopupsRoute: AdminPopupsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrustRoute: AdminTrustRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  TrustRoute: TrustRoute,
  WishlistRoute: WishlistRoute,
  ApiChatRoute: ApiChatRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  DealsSlugRoute: DealsSlugRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  ApiPublicV1CategoriesRoute: ApiPublicV1CategoriesRoute,
  ApiPublicV1CollectionsRoute: ApiPublicV1CollectionsRoute,
  ApiPublicV1DealsRoute: ApiPublicV1DealsRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1HeroSlidesRoute: ApiPublicV1HeroSlidesRoute,
  ApiPublicV1ProfileRoute: ApiPublicV1ProfileRoute,
  ApiPublicV1ReviewsRoute: ApiPublicV1ReviewsRoute,
  ApiPublicV1SettingsRoute: ApiPublicV1SettingsRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
  ApiPublicV1AdminCustomersRoute: ApiPublicV1AdminCustomersRoute,
  ApiPublicV1AdminOrdersRoute: ApiPublicV1AdminOrdersRoute,
  ApiPublicV1AdminProductsRoute: ApiPublicV1AdminProductsRoute,
  ApiPublicV1AdminStatsRoute: ApiPublicV1AdminStatsRoute,
  ApiPublicV1AuthLoginRoute: ApiPublicV1AuthLoginRoute,
  ApiPublicV1AuthLogoutRoute: ApiPublicV1AuthLogoutRoute,
  ApiPublicV1AuthRefreshRoute: ApiPublicV1AuthRefreshRoute,
  ApiPublicV1AuthSessionRoute: ApiPublicV1AuthSessionRoute,
  ApiPublicV1AuthSignupRoute: ApiPublicV1AuthSignupRoute,
  ApiPublicV1BlogSlugRoute: ApiPublicV1BlogSlugRoute,
  ApiPublicV1CouponsValidateRoute: ApiPublicV1CouponsValidateRoute,
  ApiPublicV1OrdersOrderNumberRoute: ApiPublicV1OrdersOrderNumberRoute,
  ApiPublicV1ProductsSlugRoute: ApiPublicV1ProductsSlugRoute,
  ApiPublicV1BlogIndexRoute: ApiPublicV1BlogIndexRoute,
  ApiPublicV1OrdersIndexRoute: ApiPublicV1OrdersIndexRoute,
  ApiPublicV1ProductsIndexRoute: ApiPublicV1ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
